# name: Deploy to GitHub Pages
# on:
#   push:
#     branches:
#       - main  # Ensure this matches your default branch name
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: '14'  # Adjust this to match the Node.js version you use
#       - run: npm install
#       - run: npm run build
#       - uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./dist


name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # This triggers the action when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust to match your project's Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build  # Builds your project, typically outputs to the 'dist' directory

    - name: Deploy
      uses: peaceiris/actions-main@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # The directory to deploy
        destination_dir: '.'  # Optional: Specifies the directory to deploy to in the target branch
